usr/sbin/glusterfsd
usr/sbin/gluster-georep-sshkey
usr/sbin/gluster-mountbroker
usr/sbin/gf_attach
usr/sbin/gluster-setgfid2path
usr/lib/firewalld
usr/lib/ocf
usr/lib/*/glusterfs
usr/lib/python3*/site-packages/gluster usr/lib/python3/dist-packages/
usr/lib/*/ganesha
usr/share/doc/glusterfs/glusterfs-mode.el usr/share/emacs/site-lisp/
usr/share/doc/glusterfs/benchmarking/
usr/share/glusterfs/scripts/
